DC New 52 and Rebirth from MarvelGuides and others
DieselTech/CBL-ReadingLists pull request #72
Opened 2023-10-04 19:01 UTC by flips22

MarvelGuides.com (despite its URL) just introduced a couple of DC reading lists. Also I updated some of the other universes lists to include the CV IDs.

2023-10-05 02:34 UTC, DieselTech requested changes
Lets of different problems the names of lists getting cut off.

2023-10-05 02:34 UTC, DieselTech commented on Other/unsorted/Watchmen.cbl
> +<Name>Watchme</Name>
Missing 'n' off the end.

2023-10-05 02:34 UTC, DieselTech commented on DC/Master Reading Order/Marvel Guides/2016-2021 Rebirth/Part 2 Crossover Crisis/[DC] 2016-2021 Part 2.4 The Button.cbl
> +<Name>[DC] 2016-2021 Part 2.4 The Butt</Name>
Missing last 2 letters of the name.

2023-10-05 02:34 UTC, DieselTech commented on DC/Master Reading Order/Marvel Guides/2016-2021 Rebirth/Part 2 Crossover Crisis/[DC] 2016-2021 Part 2.3 Superman Reborn.cbl
> +<Name>[DC] 2016-2021 Part 2.3 Superman Rebor</Name>
Missing 'n' at the end.

2023-10-05 02:34 UTC, DieselTech commented on DC/Master Reading Order/Marvel Guides/2016-2021 Rebirth/Part 1 Lost Time/[DC] 2016-2021 Part 1.3 Welcome to the Big Leagues.cbl
> +<Name>[DC] 2016-2021 Part 1.3 Welcome to the Big League</Name>
Missing 's' from filename

2023-10-05 02:34 UTC, DieselTech commented on DC/Master Reading Order/Marvel Guides/2016-2021 Rebirth/Part 1 Lost Time/[DC] 2016-2021 Part 1.2 Reign of the Supers.cbl
> +<Name>[DC] 2016-2021 Part 1.2 Reign of the Super</Name>
Missing 's' at end

2023-10-05 02:34 UTC, DieselTech commented on DC/Master Reading Order/Marvel Guides/2011-2016 New 52/Part 1 Point of Origin/[DC] 2011-2016 Part 1.4 The Culling.cbl
> +<Name>[DC] 2011-2016 Part 1.4 The Culling</Name>
Probably not descriptive enough of a name?

2023-10-05 02:34 UTC, DieselTech commented on DC/Master Reading Order/Marvel Guides/2011-2016 New 52/Part 1 Point of Origin/[DC] 2011-2016 Part 1.3 A League of Their Own.cbl
> +<Name>[DC] 2011-2016 Part 1.3 A League of Their Ow</Name>
Missing 'n' at end.

2023-10-05 02:34 UTC, DieselTech commented on DC/Master Reading Order/Marvel Guides/2011-2016 New 52/Part 2 Edge of Darkness/[DC] 2011-2016 Part 2.3 A Wild Storm Approaches.cbl
> +<Name>[DC] 2011-2016 Part 2.3 A Wild Storm Approache</Name>
Missing 's' at end.

2023-10-05 02:34 UTC, DieselTech commented on DC/Master Reading Order/Marvel Guides/2016-2021 Rebirth/Part 1 Lost Time/[DC] 2016-2021 Part 1.5 Generations.cbl
> +<Name>[DC] 2016-2021 Part 1.5 Generati</Name>
Missing characters at end of name.

2023-10-05 02:34 UTC, DieselTech commented on Other/unsorted/Spawn.cbl
> +<Name>Spaw</Name>
Missing 'n' at end.

2023-10-05 02:34 UTC, DieselTech commented on Other/unsorted/The Boys.cbl
> +<Name>The Boy</Name>
The Boy. Just 1.

2023-10-07 12:05 UTC, themadman0980 commented on DC/Master Reading Order/Marvel Guides/2011-2016 New 52/Part 1 Point of Origin/[DC] 2011-2016 Part 1.1 In the Beginning….cbl
Issue list and order seems all good. :)

2023-10-07 13:46 UTC, themadman0980 requested changes

2023-10-07 13:46 UTC, themadman0980 commented on DC/Master Reading Order/Marvel Guides/2011-2016 New 52/Part 2 Edge of Darkness/[DC] 2011-2016 Part 2.1 Agents of the Dark.cbl
Issue list and order seems all good. :)

2023-10-07 13:46 UTC, themadman0980 commented on DC/Master Reading Order/Marvel Guides/2011-2016 New 52/Part 2 Edge of Darkness/[DC] 2011-2016 Part 2.2 Welcome to Rotworld.cbl
Issue list and order seems all good. :)

2023-10-07 13:46 UTC, themadman0980 commented on DC/Master Reading Order/Marvel Guides/2011-2016 New 52/Part 2 Edge of Darkness/[DC] 2011-2016 Part 2.3 A Wild Storm Approaches.cbl
Issue list and order seems all good. :)

2023-10-07 13:46 UTC, themadman0980 commented on DC/Master Reading Order/Marvel Guides/2016-2021 Rebirth/Part 1 Lost Time/[DC] 2016-2021 Part 1.1 Restoring a Legacy.cbl
Issue list and order seems all good. :)

2023-10-07 13:46 UTC, themadman0980 commented on DC/Master Reading Order/Marvel Guides/2016-2021 Rebirth/Part 1 Lost Time/[DC] 2016-2021 Part 1.2 Reign of the Supers.cbl
Issue list and order seems all good. :)

2023-10-07 13:46 UTC, themadman0980 commented on DC/Master Reading Order/Marvel Guides/2016-2021 Rebirth/Part 1 Lost Time/[DC] 2016-2021 Part 1.3 Welcome to the Big Leagues.cbl
Issue list and order seems all good. :)

2023-10-07 13:46 UTC, themadman0980 commented on DC/Master Reading Order/Marvel Guides/2016-2021 Rebirth/Part 1 Lost Time/[DC] 2016-2021 Part 1.4 Monsters of Gotham.cbl
Issue list and order seems all good. :)

2023-10-07 13:46 UTC, themadman0980 commented on DC/Master Reading Order/Marvel Guides/2016-2021 Rebirth/Part 1 Lost Time/[DC] 2016-2021 Part 1.5 Generations.cbl
Missing Batgirl Annual \#1 after Batgirl \#7–12.
Otherwise, looks good.

2023-10-07 13:59 UTC, themadman0980 commented on DC/Master Reading Order/Marvel Guides/2016-2021 Rebirth/Part 2 Crossover Crisis/[DC] 2016-2021 Part 2.1 Justice League vs. Suicide Squad.cbl
List order and issues all look good. :)

2023-10-07 14:00 UTC, themadman0980 commented on DC/Master Reading Order/Marvel Guides/2016-2021 Rebirth/Part 2 Crossover Crisis/[DC] 2016-2021 Part 2.2 The Lazarus Contract.cbl
List order and issues all look good. :)

2023-10-07 14:06 UTC, themadman0980 commented on DC/Master Reading Order/Marvel Guides/2016-2021 Rebirth/Part 2 Crossover Crisis/[DC] 2016-2021 Part 2.3 Superman Reborn.cbl
List order and issues all look good. :)

2023-10-07 14:06 UTC, themadman0980 commented on DC/Master Reading Order/Marvel Guides/2016-2021 Rebirth/Part 2 Crossover Crisis/[DC] 2016-2021 Part 2.4 The Button.cbl
List order and issues all look good. :)

2023-10-10 21:42 UTC, DieselTech approved these changes

2023-10-10 21:43 UTC, merged